### ISSUE TITLE
Release sans PSR7?

### ISSUE THREAD

**Issue by jakejohns** [arbiterphp/Arbiter.Arbiter#7]
Is the *removal* of a interface type hint a major version release?
What do we think a time frame for a release with this would be? 
I'm curious to do other fun things with this now.

**Comment by pmjones** [comment]
*Relaxing* a typehint does not break BC, so no need for a major version bump. Minor, maybe. Timeframe? I am on my 2nd manhattan so not tonight ;-) but emailing myself a reminder now. If you don't see a release by Monday morning then ping me again!

**Comment by jakejohns** [comment]
Cheers!

**Comment by jakejohns** [comment]
@pmjones ping

**Comment by pmjones** [comment]
Thanks for the ping. Released! https://github.com/arbiterphp/Arbiter.Arbiter/releases/tag/1.1.0
